// Generated by tools/quiz-odds.js — do not edit by hand.
// Estimated share of quiz-takers (in %) for each exact result, from 2,000,000 simulated
// people (true-style prior {"grabfood":16,"yolo":14,"ostrich":15,"cpf":11,"hoarder":15,"crypto":12,"monk":11,"quiet":6}, answering in character 60% of the time).
// These are estimates, not live counts. Keys: persona|runnerUp|lot|little|pinch|none.
(function (root, factory) {
	if (typeof module === "object" && module.exports) {
		module.exports = factory();
	} else {
		root.QuizOdds = factory();
	}
})(typeof self !== "undefined" ? self : this, function () {
	const COMBOS = {
		"cpf|crypto|little": 0.6213,
		"cpf|crypto|lot": 0.1463,
		"cpf|crypto|pinch": 0.4569,
		"cpf|grabfood|little": 1.411,
		"cpf|grabfood|lot": 0.5503,
		"cpf|grabfood|pinch": 1.2339,
		"cpf|hoarder|little": 1.1514,
		"cpf|hoarder|lot": 0.5547,
		"cpf|hoarder|pinch": 1.0673,
		"cpf|monk|little": 0.5159,
		"cpf|monk|lot": 0.3604,
		"cpf|monk|pinch": 0.2226,
		"cpf|ostrich|little": 1.3036,
		"cpf|ostrich|lot": 0.4923,
		"cpf|ostrich|pinch": 1.7496,
		"cpf|yolo|little": 1.5545,
		"cpf|yolo|lot": 0.5759,
		"cpf|yolo|pinch": 1.4025,
		"crypto|cpf|little": 0.7631,
		"crypto|cpf|lot": 0.3784,
		"crypto|cpf|pinch": 0.5751,
		"crypto|grabfood|little": 1.3779,
		"crypto|grabfood|lot": 0.4485,
		"crypto|grabfood|pinch": 1.2948,
		"crypto|hoarder|little": 1.3698,
		"crypto|hoarder|lot": 0.6502,
		"crypto|hoarder|pinch": 1.4799,
		"crypto|monk|little": 0.6324,
		"crypto|monk|lot": 0.3454,
		"crypto|monk|pinch": 0.3617,
		"crypto|ostrich|little": 0.7516,
		"crypto|ostrich|lot": 0.3903,
		"crypto|ostrich|pinch": 1.0925,
		"crypto|yolo|little": 1.5618,
		"crypto|yolo|lot": 0.6802,
		"crypto|yolo|pinch": 1.5944,
		"grabfood|cpf|little": 2.3929,
		"grabfood|cpf|lot": 0.6671,
		"grabfood|cpf|pinch": 0.8649,
		"grabfood|crypto|little": 1.9322,
		"grabfood|crypto|lot": 0.5252,
		"grabfood|crypto|pinch": 0.9853,
		"grabfood|hoarder|little": 0.6192,
		"grabfood|hoarder|lot": 0.2302,
		"grabfood|hoarder|pinch": 0.3719,
		"grabfood|monk|little": 0.2458,
		"grabfood|monk|lot": 0.1265,
		"grabfood|monk|pinch": 0.1466,
		"grabfood|ostrich|little": 1.5827,
		"grabfood|ostrich|lot": 0.3485,
		"grabfood|ostrich|pinch": 0.9799,
		"grabfood|yolo|little": 1.9999,
		"grabfood|yolo|lot": 0.5396,
		"grabfood|yolo|pinch": 0.9451,
		"hoarder|cpf|little": 3.0868,
		"hoarder|cpf|lot": 1.1328,
		"hoarder|cpf|pinch": 1.2239,
		"hoarder|crypto|little": 2.9908,
		"hoarder|crypto|lot": 0.815,
		"hoarder|crypto|pinch": 1.1011,
		"hoarder|grabfood|little": 0.7777,
		"hoarder|grabfood|lot": 0.2718,
		"hoarder|grabfood|pinch": 0.2561,
		"hoarder|monk|little": 0.2502,
		"hoarder|monk|lot": 0.0971,
		"hoarder|monk|pinch": 0.1566,
		"hoarder|ostrich|little": 1.1916,
		"hoarder|ostrich|lot": 0.3077,
		"hoarder|ostrich|pinch": 0.8369,
		"hoarder|yolo|little": 0.8065,
		"hoarder|yolo|lot": 0.1771,
		"hoarder|yolo|pinch": 0.3297,
		"monk|cpf|little": 0.6765,
		"monk|cpf|lot": 0.4629,
		"monk|cpf|pinch": 0.0657,
		"monk|crypto|little": 0.9706,
		"monk|crypto|lot": 0.5167,
		"monk|crypto|pinch": 0.0919,
		"monk|grabfood|little": 0.4264,
		"monk|grabfood|lot": 0.2684,
		"monk|grabfood|pinch": 0.1504,
		"monk|hoarder|little": 0.2051,
		"monk|hoarder|lot": 0.1127,
		"monk|hoarder|pinch": 0.0556,
		"monk|ostrich|little": 0.6504,
		"monk|ostrich|lot": 0.2524,
		"monk|ostrich|pinch": 0.1494,
		"monk|yolo|little": 0.3698,
		"monk|yolo|lot": 0.3543,
		"monk|yolo|pinch": 0.1954,
		"ostrich|cpf|little": 2.2396,
		"ostrich|cpf|lot": 0.4985,
		"ostrich|cpf|pinch": 1.1704,
		"ostrich|crypto|little": 1.1702,
		"ostrich|crypto|lot": 0.2952,
		"ostrich|crypto|pinch": 0.886,
		"ostrich|grabfood|little": 1.686,
		"ostrich|grabfood|lot": 0.3423,
		"ostrich|grabfood|pinch": 1.1197,
		"ostrich|hoarder|little": 0.4163,
		"ostrich|hoarder|lot": 0.2681,
		"ostrich|hoarder|pinch": 0.429,
		"ostrich|monk|little": 0.165,
		"ostrich|monk|lot": 0.1581,
		"ostrich|monk|pinch": 0.0532,
		"ostrich|yolo|little": 2.2167,
		"ostrich|yolo|lot": 0.596,
		"ostrich|yolo|pinch": 1.7463,
		"quiet|cpf|pinch": 0.0551,
		"quiet|crypto|pinch": 0.0402,
		"quiet|grabfood|pinch": 0.0506,
		"quiet|hoarder|little": 0.0037,
		"quiet|hoarder|pinch": 0.0906,
		"quiet|monk|pinch": 0.0508,
		"quiet|ostrich|pinch": 0.0544,
		"quiet|yolo|pinch": 0.0408,
		"yolo|cpf|little": 1.7486,
		"yolo|cpf|lot": 0.6055,
		"yolo|cpf|pinch": 1.2132,
		"yolo|crypto|little": 2.1933,
		"yolo|crypto|lot": 0.4825,
		"yolo|crypto|pinch": 1.2164,
		"yolo|grabfood|little": 1.8772,
		"yolo|grabfood|lot": 0.4874,
		"yolo|grabfood|pinch": 0.9569,
		"yolo|hoarder|little": 0.5498,
		"yolo|hoarder|lot": 0.2927,
		"yolo|hoarder|pinch": 0.3194,
		"yolo|monk|little": 0.3123,
		"yolo|monk|lot": 0.2501,
		"yolo|monk|pinch": 0.1228,
		"yolo|ostrich|little": 1.4857,
		"yolo|ostrich|lot": 0.4796,
		"yolo|ostrich|pinch": 1.1613
	};
	const PERSONAS = {"cpf":15.3699,"crypto":15.7476,"grabfood":15.5031,"hoarder":15.8089,"monk":5.9742,"ostrich":15.4563,"quiet":0.3861,"yolo":15.7542};

	function tierOf(line) {
		if (/a lot of/.test(line)) return "lot";
		if (/a little bit of/.test(line)) return "little";
		if (/a pinch of/.test(line)) return "pinch";
		return "none";
	}

	// Share (%) of people who get this exact result, or the persona's share if
	// the combination never came up in the simulation.
	function percentFor(result, line) {
		const id = `${result.key}|${result.runnerUp || "none"}|${tierOf(line || "")}`;
		return COMBOS[id] || PERSONAS[result.key] / 50 || 0.01;
	}

	// "about 1 in 40 people" style wording.
	function describe(percent) {
		const oneIn = Math.max(2, Math.round(100 / Math.max(percent, 0.001)));
		const nice = oneIn < 20 ? oneIn : oneIn < 100 ? Math.round(oneIn / 5) * 5 : oneIn < 1000 ? Math.round(oneIn / 10) * 10 : Math.round(oneIn / 100) * 100;
		const pct = percent >= 1 ? `${percent.toFixed(1).replace(/\.0$/, "")}%` : percent >= 0.1 ? `${percent.toFixed(1)}%` : "under 0.1%";
		return { oneIn: nice, percent: pct, text: `${percent < 0.1 ? "Fewer than 0.1%" : pct} of people get this exact result (about 1 in ${nice.toLocaleString("en")})` };
	}

	return { COMBOS, PERSONAS, percentFor, describe };
});
