// Builds js/shared/quizOdds.js: how common each exact result is (persona +
// runner-up + how strong the runner-up is), from the simulated crowd in
// quiz-sim.js. Run: node tools/quiz-odds.js
const fs = require("fs");
const path = require("path");
const Quiz = require("../js/shared/moneyQuiz.js");
const { simulate, PRIOR, CONSISTENCY } = require("./quiz-sim.js");

const N = 2000000;
const results = simulate(N, 2026);
const combos = {};
const personas = {};
results.forEach((r) => {
	const line = Quiz.runnerUpLine(r);
	const tier = /a lot of/.test(line) ? "lot" : /a little bit of/.test(line) ? "little" : /a pinch of/.test(line) ? "pinch" : "none";
	const id = `${r.key}|${r.runnerUp || "none"}|${tier}`;
	combos[id] = (combos[id] || 0) + 1;
	personas[r.key] = (personas[r.key] || 0) + 1;
});
const share = (n) => Math.round((1e6 * n) / N) / 1e4; // percent, 4 dp
const out = {};
Object.keys(combos).sort().forEach((k) => { out[k] = share(combos[k]); });
const byPersona = {};
Object.keys(personas).sort().forEach((k) => { byPersona[k] = share(personas[k]); });

const file = `// Generated by tools/quiz-odds.js — do not edit by hand.
// Estimated share of quiz-takers (in %) for each exact result, from ${N.toLocaleString("en")} simulated
// people (true-style prior ${JSON.stringify(PRIOR)}, answering in character ${CONSISTENCY * 100}% of the time).
// These are estimates, not live counts. Keys: persona|runnerUp|lot|little|pinch|none.
(function (root, factory) {
	if (typeof module === "object" && module.exports) {
		module.exports = factory();
	} else {
		root.QuizOdds = factory();
	}
})(typeof self !== "undefined" ? self : this, function () {
	const COMBOS = ${JSON.stringify(out, null, "\t").replace(/\n/g, "\n\t")};
	const PERSONAS = ${JSON.stringify(byPersona)};

	function tierOf(line) {
		if (/a lot of/.test(line)) return "lot";
		if (/a little bit of/.test(line)) return "little";
		if (/a pinch of/.test(line)) return "pinch";
		return "none";
	}

	// Share (%) of people who get this exact result, or the persona's share if
	// the combination never came up in the simulation.
	function percentFor(result, line) {
		const id = \`\${result.key}|\${result.runnerUp || "none"}|\${tierOf(line || "")}\`;
		return COMBOS[id] || PERSONAS[result.key] / 50 || 0.01;
	}

	// "about 1 in 40 people" style wording.
	function describe(percent) {
		const oneIn = Math.max(2, Math.round(100 / Math.max(percent, 0.001)));
		const nice = oneIn < 20 ? oneIn : oneIn < 100 ? Math.round(oneIn / 5) * 5 : oneIn < 1000 ? Math.round(oneIn / 10) * 10 : Math.round(oneIn / 100) * 100;
		const pct = percent >= 1 ? \`\${percent.toFixed(1).replace(/\\.0$/, "")}%\` : percent >= 0.1 ? \`\${percent.toFixed(1)}%\` : "under 0.1%";
		return { oneIn: nice, percent: pct, text: \`\${percent < 0.1 ? "Fewer than 0.1%" : pct} of people get this exact result (about 1 in \${nice.toLocaleString("en")})\` };
	}

	return { COMBOS, PERSONAS, percentFor, describe };
});
`;
fs.writeFileSync(path.join(__dirname, "../js/shared/quizOdds.js"), file);
console.log("combos:", Object.keys(out).length);
const top = Object.entries(out).sort((a, b) => b[1] - a[1]);
console.log("most common:", top.slice(0, 5));
console.log("rarest:", top.slice(-5));
console.log("personas:", byPersona);
